# .readthedocs.yaml
# Konfigurasi untuk Read the Docs

version: 2

# Tentukan sistem operasi dan versi Python
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Beri tahu Read the Docs bahwa kita menggunakan MkDocs
mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

# Tentukan cara menginstal dependensi Python
python:
  install:
    - requirements: requirements-docs.txt