"""optimize_database_indexes

Revision ID: 2210f33597f3
Revises: a1b2c3d4e5f6
Create Date: 2025-10-05 09:54:41.079816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2210f33597f3'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if payment_callback_logs table exists before dropping
    try:
        # Drop indexes only if they exist
        op.drop_index(op.f('idx_callback_log_external_id'), table_name='payment_callback_logs')
        op.drop_index(op.f('idx_callback_log_idempotency_key'), table_name='payment_callback_logs')
        op.drop_index(op.f('idx_callback_log_status'), table_name='payment_callback_logs')
        op.drop_index(op.f('idx_callback_log_xendit_id'), table_name='payment_callback_logs')
        op.drop_index(op.f('ix_payment_callback_logs_external_id'), table_name='payment_callback_logs')
        op.drop_index(op.f('ix_payment_callback_logs_id'), table_name='payment_callback_logs')
        op.drop_index(op.f('ix_payment_callback_logs_idempotency_key'), table_name='payment_callback_logs')
        op.drop_index(op.f('ix_payment_callback_logs_xendit_id'), table_name='payment_callback_logs')

        # Drop table if it exists
        op.drop_table('payment_callback_logs')
    except:
        # Table or indexes don't exist, skip payment_callback_logs operations
        pass
    # Drop data_teknis indexes with error handling
    data_teknis_indexes_to_drop = [
        'idx_datateknis_id_pelanggan',
        'idx_datateknis_id_vlan',
        'idx_datateknis_mikrotik_server_id',
        'idx_datateknis_odc',
        'idx_datateknis_odp_id',
        'idx_datateknis_odp_port',
        'idx_datateknis_olt',
        'idx_datateknis_olt_custom',
        'idx_datateknis_onu_power',
        'idx_datateknis_otb',
        'idx_datateknis_pon',
        'idx_datateknis_port_odp',
        'idx_datateknis_pppoe',
        'idx_datateknis_profile_pppoe',
        'idx_datateknis_sn',
        'idx_datateknis_speedtest_proof'
    ]

    for index_name in data_teknis_indexes_to_drop:
        try:
            op.drop_index(index_name, table_name='data_teknis')
        except:
            # Index doesn't exist, skip
            pass
    # Create data_teknis indexes with error handling (skip if already exists)
    data_teknis_indexes_to_create = [
        ('idx_datateknis_odp_location', ['odp_id', 'port_odp']),
        ('idx_datateknis_olt_port', ['olt', 'pon']),
        ('idx_datateknis_onu_status', ['onu_power', 'mikrotik_sync_pending']),
        ('idx_datateknis_pppoe_credentials', ['id_pelanggan', 'password_pppoe'])
    ]

    for index_name, columns in data_teknis_indexes_to_create:
        try:
            op.create_index(index_name, 'data_teknis', columns, unique=False)
        except:
            # Index already exists, skip
            pass
    # Drop invoice indexes with error handling
    invoice_indexes_to_drop = [
        'idx_invoice_brand_date',
        'idx_invoice_monthly_summary',
        'idx_invoice_payment_date',
        'ix_invoices_status_invoice',
        'ix_invoices_tgl_jatuh_tempo',
        'ix_invoices_xendit_external_id'
    ]

    # Skip indexes that might be needed by foreign key constraints
    # 'ix_invoices_pelanggan_id'  # Needed by foreign key constraint
    # 'idx_invoice_status_paid_date'  # Might be needed by queries

    for index_name in invoice_indexes_to_drop:
        try:
            op.drop_index(index_name, table_name='invoices')
        except:
            # Index doesn't exist, skip
            pass
    # Create invoice indexes with error handling (skip if already exists)
    invoice_indexes_to_create = [
        ('idx_invoice_brand_revenue', ['brand', 'tgl_invoice', 'total_harga']),
        ('idx_invoice_customer_status', ['pelanggan_id', 'status_invoice']),
        ('idx_invoice_date_range', ['tgl_invoice', 'tgl_jatuh_tempo']),
        ('idx_invoice_number_lookup', ['invoice_number', 'status_invoice']),
        ('idx_invoice_payment_method', ['metode_pembayaran', 'status_invoice']),
        ('idx_invoice_payment_tracking', ['status_invoice', 'paid_at']),
        ('idx_invoice_revenue_analysis', ['status_invoice', 'tgl_invoice', 'total_harga']),
        ('idx_invoice_status_brand', ['status_invoice', 'brand']),
        ('idx_invoice_xendit_lookup', ['xendit_id', 'status_invoice'])
    ]

    for index_name, columns in invoice_indexes_to_create:
        try:
            op.create_index(index_name, 'invoices', columns, unique=False)
        except:
            # Index already exists, skip
            pass

    # Create basic indexes if they don't exist
    try:
        op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    except:
        pass
    try:
        op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    except:
        pass
    # Drop langganan indexes with error handling
    langganan_indexes_to_drop = [
        'idx_langganan_active_customer',
        'idx_langganan_due_analysis',
        'idx_langganan_package_customer',
        'idx_langganan_status_count'
    ]

    for index_name in langganan_indexes_to_drop:
        try:
            op.drop_index(index_name, table_name='langganan')
        except:
            # Index doesn't exist, skip
            pass
    # Create langganan indexes with error handling (skip if already exists)
    langganan_indexes_to_create = [
        ('idx_langganan_active_subscriptions', ['status', 'paket_layanan_id']),
        ('idx_langganan_customer_package', ['pelanggan_id', 'paket_layanan_id', 'status']),
        ('idx_langganan_customer_status', ['pelanggan_id', 'status']),
        ('idx_langganan_due_date', ['status', 'tgl_jatuh_tempo']),
        ('idx_langganan_package_status', ['paket_layanan_id', 'status']),
        ('idx_langganan_payment_analysis', ['metode_pembayaran', 'status', 'tgl_jatuh_tempo']),
        ('idx_langganan_subscription_dates', ['tgl_mulai_langganan', 'tgl_jatuh_tempo', 'tgl_berhenti'])
    ]

    for index_name, columns in langganan_indexes_to_create:
        try:
            op.create_index(index_name, 'langganan', columns, unique=False)
        except:
            # Index already exists, skip
            pass

    # Create basic indexes if they don't exist
    basic_langganan_indexes = [
        ('ix_langganan_created_at', ['created_at']),
        ('ix_langganan_harga_awal', ['harga_awal']),
        ('ix_langganan_id', ['id']),
        ('ix_langganan_metode_pembayaran', ['metode_pembayaran']),
        ('ix_langganan_paket_layanan_id', ['paket_layanan_id']),
        ('ix_langganan_tgl_berhenti', ['tgl_berhenti']),
        ('ix_langganan_tgl_invoice_terakhir', ['tgl_invoice_terakhir']),
        ('ix_langganan_tgl_mulai_langganan', ['tgl_mulai_langganan']),
        ('ix_langganan_updated_at', ['updated_at'])
    ]

    for index_name, columns in basic_langganan_indexes:
        try:
            op.create_index(op.f(index_name), 'langganan', columns, unique=False)
        except:
            # Index already exists, skip
            pass
    op.create_index('idx_mikrotik_active_host', 'mikrotik_servers', ['is_active', 'host_ip'], unique=False)
    op.create_index('idx_mikrotik_active_status', 'mikrotik_servers', ['is_active', 'last_connection_status'], unique=False)
    op.create_index('idx_mikrotik_host_name', 'mikrotik_servers', ['host_ip', 'name'], unique=False)
    op.create_index('idx_mikrotik_is_active', 'mikrotik_servers', ['is_active'], unique=False)
    op.create_index('idx_mikrotik_last_connected_at', 'mikrotik_servers', ['last_connected_at'], unique=False)
    op.create_index('idx_mikrotik_last_connection_status', 'mikrotik_servers', ['last_connection_status'], unique=False)
    op.create_index('idx_mikrotik_ros_version', 'mikrotik_servers', ['ros_version'], unique=False)
    op.create_index(op.f('ix_mikrotik_servers_created_at'), 'mikrotik_servers', ['created_at'], unique=False)
    op.create_index(op.f('ix_mikrotik_servers_id'), 'mikrotik_servers', ['id'], unique=False)
    op.create_index(op.f('ix_mikrotik_servers_last_connected_at'), 'mikrotik_servers', ['last_connected_at'], unique=False)
    op.create_index(op.f('ix_mikrotik_servers_port'), 'mikrotik_servers', ['port'], unique=False)
    op.create_index(op.f('ix_mikrotik_servers_ros_version'), 'mikrotik_servers', ['ros_version'], unique=False)
    op.create_index(op.f('ix_mikrotik_servers_updated_at'), 'mikrotik_servers', ['updated_at'], unique=False)
    op.create_index(op.f('ix_mikrotik_servers_username'), 'mikrotik_servers', ['username'], unique=False)
    op.drop_index(op.f('idx_pelanggan_active_subscription'), table_name='pelanggan')
    op.drop_index(op.f('idx_pelanggan_installation_month'), table_name='pelanggan')
    op.drop_index(op.f('idx_pelanggan_location_count'), table_name='pelanggan')
    op.drop_index(op.f('ix_pelanggan_alamat'), table_name='pelanggan')
    op.drop_index(op.f('ix_pelanggan_id_brand'), table_name='pelanggan')
    op.drop_index(op.f('ix_pelanggan_nama'), table_name='pelanggan')
    op.drop_index(op.f('ix_pelanggan_no_telp'), table_name='pelanggan')
    op.create_index('idx_pelanggan_blok_unit', 'pelanggan', ['blok', 'unit'], unique=False)
    op.create_index('idx_pelanggan_brand_status', 'pelanggan', ['id_brand', 'layanan'], unique=False)
    op.create_index('idx_pelanggan_installation_trends', 'pelanggan', ['tgl_instalasi', 'id_brand'], unique=False)
    op.create_index('idx_pelanggan_ktp_email', 'pelanggan', ['no_ktp', 'email'], unique=False)
    op.create_index('idx_pelanggan_nama_alamat', 'pelanggan', ['nama', 'alamat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pelanggan_nama_alamat', table_name='pelanggan')
    op.drop_index('idx_pelanggan_ktp_email', table_name='pelanggan')
    op.drop_index('idx_pelanggan_installation_trends', table_name='pelanggan')
    op.drop_index('idx_pelanggan_brand_status', table_name='pelanggan')
    op.drop_index('idx_pelanggan_blok_unit', table_name='pelanggan')
    op.create_index(op.f('ix_pelanggan_no_telp'), 'pelanggan', ['no_telp'], unique=False)
    op.create_index(op.f('ix_pelanggan_nama'), 'pelanggan', ['nama'], unique=False)
    op.create_index(op.f('ix_pelanggan_id_brand'), 'pelanggan', ['id_brand'], unique=False)
    op.create_index(op.f('ix_pelanggan_alamat'), 'pelanggan', ['alamat'], unique=False)
    op.create_index(op.f('idx_pelanggan_location_count'), 'pelanggan', ['alamat', 'id'], unique=False)
    op.create_index(op.f('idx_pelanggan_installation_month'), 'pelanggan', ['tgl_instalasi', 'id_brand'], unique=False)
    op.create_index(op.f('idx_pelanggan_active_subscription'), 'pelanggan', ['id', 'layanan'], unique=False)
    op.drop_index(op.f('ix_mikrotik_servers_username'), table_name='mikrotik_servers')
    op.drop_index(op.f('ix_mikrotik_servers_updated_at'), table_name='mikrotik_servers')
    op.drop_index(op.f('ix_mikrotik_servers_ros_version'), table_name='mikrotik_servers')
    op.drop_index(op.f('ix_mikrotik_servers_port'), table_name='mikrotik_servers')
    op.drop_index(op.f('ix_mikrotik_servers_last_connected_at'), table_name='mikrotik_servers')
    op.drop_index(op.f('ix_mikrotik_servers_id'), table_name='mikrotik_servers')
    op.drop_index(op.f('ix_mikrotik_servers_created_at'), table_name='mikrotik_servers')
    op.drop_index('idx_mikrotik_ros_version', table_name='mikrotik_servers')
    op.drop_index('idx_mikrotik_last_connection_status', table_name='mikrotik_servers')
    op.drop_index('idx_mikrotik_last_connected_at', table_name='mikrotik_servers')
    op.drop_index('idx_mikrotik_is_active', table_name='mikrotik_servers')
    op.drop_index('idx_mikrotik_host_name', table_name='mikrotik_servers')
    op.drop_index('idx_mikrotik_active_status', table_name='mikrotik_servers')
    op.drop_index('idx_mikrotik_active_host', table_name='mikrotik_servers')
    op.drop_index(op.f('ix_langganan_updated_at'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_tgl_mulai_langganan'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_tgl_invoice_terakhir'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_tgl_berhenti'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_paket_layanan_id'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_metode_pembayaran'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_id'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_harga_awal'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_created_at'), table_name='langganan')
    op.drop_index('idx_langganan_subscription_dates', table_name='langganan')
    op.drop_index('idx_langganan_payment_analysis', table_name='langganan')
    op.drop_index('idx_langganan_package_status', table_name='langganan')
    op.drop_index('idx_langganan_due_date', table_name='langganan')
    op.drop_index('idx_langganan_customer_status', table_name='langganan')
    op.drop_index('idx_langganan_customer_package', table_name='langganan')
    op.drop_index('idx_langganan_active_subscriptions', table_name='langganan')
    op.create_index(op.f('idx_langganan_status_count'), 'langganan', ['status', 'pelanggan_id'], unique=False)
    op.create_index(op.f('idx_langganan_package_customer'), 'langganan', ['paket_layanan_id', 'pelanggan_id', 'status'], unique=False)
    op.create_index(op.f('idx_langganan_due_analysis'), 'langganan', ['tgl_jatuh_tempo', 'status', 'metode_pembayaran'], unique=False)
    op.create_index(op.f('idx_langganan_active_customer'), 'langganan', ['status', 'paket_layanan_id'], unique=False)
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index('idx_invoice_xendit_lookup', table_name='invoices')
    op.drop_index('idx_invoice_status_brand', table_name='invoices')
    op.drop_index('idx_invoice_revenue_analysis', table_name='invoices')
    op.drop_index('idx_invoice_payment_tracking', table_name='invoices')
    op.drop_index('idx_invoice_payment_method', table_name='invoices')
    op.drop_index('idx_invoice_number_lookup', table_name='invoices')
    op.drop_index('idx_invoice_date_range', table_name='invoices')
    op.drop_index('idx_invoice_customer_status', table_name='invoices')
    op.drop_index('idx_invoice_brand_revenue', table_name='invoices')
    op.create_index(op.f('ix_invoices_xendit_external_id'), 'invoices', ['xendit_external_id'], unique=False)
    op.create_index(op.f('ix_invoices_tgl_jatuh_tempo'), 'invoices', ['tgl_jatuh_tempo'], unique=False)
    op.create_index(op.f('ix_invoices_status_invoice'), 'invoices', ['status_invoice'], unique=False)
    op.create_index(op.f('ix_invoices_pelanggan_id'), 'invoices', ['pelanggan_id'], unique=False)
    op.create_index(op.f('idx_invoice_status_paid_date'), 'invoices', ['status_invoice', 'paid_at', 'total_harga'], unique=False)
    op.create_index(op.f('idx_invoice_payment_date'), 'invoices', ['paid_at', 'tgl_jatuh_tempo'], unique=False)
    op.create_index(op.f('idx_invoice_monthly_summary'), 'invoices', ['status_invoice', 'tgl_invoice', 'total_harga'], unique=False)
    op.create_index(op.f('idx_invoice_brand_date'), 'invoices', ['brand', 'tgl_invoice'], unique=False)
    op.drop_index('idx_datateknis_pppoe_credentials', table_name='data_teknis')
    op.drop_index('idx_datateknis_onu_status', table_name='data_teknis')
    op.drop_index('idx_datateknis_olt_port', table_name='data_teknis')
    op.drop_index('idx_datateknis_odp_location', table_name='data_teknis')
    op.create_index(op.f('idx_datateknis_speedtest_proof'), 'data_teknis', ['speedtest_proof'], unique=False)
    op.create_index(op.f('idx_datateknis_sn'), 'data_teknis', ['sn'], unique=False)
    op.create_index(op.f('idx_datateknis_profile_pppoe'), 'data_teknis', ['profile_pppoe'], unique=False)
    op.create_index(op.f('idx_datateknis_pppoe'), 'data_teknis', ['id_pelanggan', 'password_pppoe'], unique=False)
    op.create_index(op.f('idx_datateknis_port_odp'), 'data_teknis', ['port_odp'], unique=False)
    op.create_index(op.f('idx_datateknis_pon'), 'data_teknis', ['pon'], unique=False)
    op.create_index(op.f('idx_datateknis_otb'), 'data_teknis', ['otb'], unique=False)
    op.create_index(op.f('idx_datateknis_onu_power'), 'data_teknis', ['onu_power'], unique=False)
    op.create_index(op.f('idx_datateknis_olt_custom'), 'data_teknis', ['olt_custom'], unique=False)
    op.create_index(op.f('idx_datateknis_olt'), 'data_teknis', ['olt'], unique=False)
    op.create_index(op.f('idx_datateknis_odp_port'), 'data_teknis', ['odp_id', 'port_odp'], unique=False)
    op.create_index(op.f('idx_datateknis_odp_id'), 'data_teknis', ['odp_id'], unique=False)
    op.create_index(op.f('idx_datateknis_odc'), 'data_teknis', ['odc'], unique=False)
    op.create_index(op.f('idx_datateknis_mikrotik_server_id'), 'data_teknis', ['mikrotik_server_id'], unique=False)
    op.create_index(op.f('idx_datateknis_id_vlan'), 'data_teknis', ['id_vlan'], unique=False)
    op.create_index(op.f('idx_datateknis_id_pelanggan'), 'data_teknis', ['id_pelanggan'], unique=False)
    op.create_table('payment_callback_logs',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('xendit_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('external_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('callback_data', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('processed_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_payment_callback_logs_xendit_id'), 'payment_callback_logs', ['xendit_id'], unique=False)
    op.create_index(op.f('ix_payment_callback_logs_idempotency_key'), 'payment_callback_logs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_payment_callback_logs_id'), 'payment_callback_logs', ['id'], unique=False)
    op.create_index(op.f('ix_payment_callback_logs_external_id'), 'payment_callback_logs', ['external_id'], unique=False)
    op.create_index(op.f('idx_callback_log_xendit_id'), 'payment_callback_logs', ['xendit_id'], unique=False)
    op.create_index(op.f('idx_callback_log_status'), 'payment_callback_logs', ['status'], unique=False)
    op.create_index(op.f('idx_callback_log_idempotency_key'), 'payment_callback_logs', ['idempotency_key'], unique=False)
    op.create_index(op.f('idx_callback_log_external_id'), 'payment_callback_logs', ['external_id'], unique=False)
    # ### end Alembic commands ###
