"""Add revoked_before to User model and timestamps to Pelanggan

Revision ID: 267262874499
Revises: 7b55743fbc96
Create Date: 2025-09-21 21:44:28.696959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267262874499'
down_revision: Union[str, Sequence[str], None] = '7b55743fbc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pelanggan', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('pelanggan', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('revoked_before', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'revoked_before')
    op.drop_column('pelanggan', 'updated_at')
    op.drop_column('pelanggan', 'created_at')
    # ### end Alembic commands ###
