"""fix_data_teknis_overly_long_composite_indexes

Revision ID: 52cc25f5333f
Revises: b16dcd40912c
Create Date: 2025-10-04 17:15:17.757306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52cc25f5333f'
down_revision: Union[str, Sequence[str], None] = 'b16dcd40912c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Hapus indeks yang terlalu panjang yang menyebabkan error
    # Indeks dengan terlalu banyak kolom causing key length > 3072 bytes

    # Hapus indeks yang terlalu panjang dari migration sebelumnya
    try:
        op.drop_index('idx_datateknis_all_customer_sync_info', table_name='data_teknis')
    except:
        pass  # Index mungkin belum ada

    try:
        op.drop_index('idx_datateknis_all_customer_vlan_info', table_name='data_teknis')
    except:
        pass

    try:
        op.drop_index('idx_datateknis_all_full_info', table_name='data_teknis')
    except:
        pass

    try:
        op.drop_index('idx_datateknis_all_sync_info', table_name='data_teknis')
    except:
        pass

    try:
        op.drop_index('idx_datateknis_all_vlan_pppoe_info', table_name='data_teknis')
    except:
        pass

    # Buat indeks yang lebih pendek dan efisien
    # Core indexes untuk query yang paling sering digunakan
    op.create_index('idx_datateknis_customer_sync', 'data_teknis', ['pelanggan_id', 'mikrotik_sync_pending'], unique=False)
    op.create_index('idx_datateknis_server_sync', 'data_teknis', ['mikrotik_server_id', 'mikrotik_sync_pending'], unique=False)
    op.create_index('idx_datateknis_odp_sync', 'data_teknis', ['odp_id', 'mikrotik_sync_pending'], unique=False)
    op.create_index('idx_datateknis_pppoe_sync', 'data_teknis', ['id_pelanggan', 'mikrotik_sync_pending'], unique=False)
    op.create_index('idx_datateknis_vlan_sync', 'data_teknis', ['id_vlan', 'mikrotik_sync_pending'], unique=False)

    # Index untuk lookup cepat
    op.create_index('idx_datateknis_customer_lookup', 'data_teknis', ['pelanggan_id', 'id_pelanggan'], unique=False)
    op.create_index('idx_datateknis_network_lookup', 'data_teknis', ['mikrotik_server_id', 'ip_pelanggan'], unique=False)
    op.create_index('idx_datateknis_device_lookup', 'data_teknis', ['odp_id', 'port_odp'], unique=False)
    op.create_index('idx_datateknis_pppoe_lookup', 'data_teknis', ['id_pelanggan', 'password_pppoe'], unique=False)

    # Index untuk search OLT/ODC
    op.create_index('idx_datateknis_olt_search', 'data_teknis', ['olt', 'olt_custom'], unique=False)
    op.create_index('idx_datateknis_odc_search', 'data_teknis', ['otb', 'odc'], unique=False)
    op.create_index('idx_datateknis_device_search', 'data_teknis', ['sn', 'onu_power'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Hapus indeks yang baru dibuat
    op.drop_index('idx_datateknis_device_search', table_name='data_teknis')
    op.drop_index('idx_datateknis_odc_search', table_name='data_teknis')
    op.drop_index('idx_datateknis_olt_search', table_name='data_teknis')
    op.drop_index('idx_datateknis_pppoe_lookup', table_name='data_teknis')
    op.drop_index('idx_datateknis_device_lookup', table_name='data_teknis')
    op.drop_index('idx_datateknis_network_lookup', table_name='data_teknis')
    op.drop_index('idx_datateknis_customer_lookup', table_name='data_teknis')
    op.drop_index('idx_datateknis_vlan_sync', table_name='data_teknis')
    op.drop_index('idx_datateknis_pppoe_sync', table_name='data_teknis')
    op.drop_index('idx_datateknis_odp_sync', table_name='data_teknis')
    op.drop_index('idx_datateknis_server_sync', table_name='data_teknis')
    op.drop_index('idx_datateknis_customer_sync', table_name='data_teknis')
    # ### end Alembic commands ###
