"""cleanup_langganan_over_indexing_optimize_performance

Revision ID: 8481b912af1f
Revises: 52cc25f5333f
Create Date: 2025-10-04 17:30:32.278426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8481b912af1f'
down_revision: Union[str, Sequence[str], None] = '52cc25f5333f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop ALL the over-indexed indexes from langganan table for MASSIVE performance boost!
    # WARNING: This will drop 70+ redundant indexes to improve write performance

    # Drop major composite indexes that are redundant
    redundant_indexes = [
        'idx_langganan_all_combined_filters',
        'idx_langganan_all_core_fields',
        'idx_langganan_all_created_filters',
        'idx_langganan_all_customer_dates',
        'idx_langganan_all_customer_fields',
        'idx_langganan_all_customer_method_status',
        'idx_langganan_all_customer_package_dates',
        'idx_langganan_all_customer_package_method',
        'idx_langganan_all_customer_package_status',
        'idx_langganan_all_customer_package_status_dates',
        'idx_langganan_all_customer_package_status_method',
        'idx_langganan_all_customer_package_status_method_dates',
        'idx_langganan_all_customer_package_status_method_price_dates',
        'idx_langganan_all_customer_package_status_method_price_dates_created',
        'idx_langganan_all_customer_package_status_method_price_dates_created_updated',
        'idx_langganan_all_customer_package_status_method_price_dates_updated',
        'idx_langganan_all_customer_status',
        'idx_langganan_all_customer_status_dates',
        'idx_langganan_all_customer_status_method',
        'idx_langganan_all_date_fields',
        'idx_langganan_all_date_filters',
        'idx_langganan_all_dates',
        'idx_langganan_all_filters',
        'idx_langganan_all_invoice_fields',
        'idx_langganan_all_amount_fields',
        'idx_langganan_all_method_dates',
        'idx_langganan_all_method_status',
        'idx_langganan_all_payment_fields',
        'idx_langganan_all_price_filters',
        'idx_langganan_all_processing_fields',
        'idx_langganan_all_status_fields',
        'idx_langganan_all_status_method',
        'idx_langganan_all_status_dates',
        'idx_langganan_all_package_dates',
        'idx_langganan_all_package_method_status',
        'idx_langganan_all_package_status',
        'idx_langganan_all_package_status_dates',
        'idx_langganan_all_package_status_method'
    ]

    for index_name in redundant_indexes:
        try:
            op.drop_index(index_name, table_name='langganan')
        except:
            pass  # Index might not exist, continue

    # Drop redundant individual indexes
    redundant_single_indexes = [
        'idx_langganan_customer_package_status',
        'idx_langganan_customer_created',
        'idx_langganan_customer_dates',
        'idx_langganan_customer_invoice',
        'idx_langganan_customer_method',
        'idx_langganan_customer_method_status',
        'idx_langganan_customer_package',
        'idx_langganan_customer_package_invoice',
        'idx_langganan_customer_price',
        'idx_langganan_date_range_status',
        'idx_langganan_dates',
        'idx_langganan_due_date',
        'idx_langganan_end_date',
        'idx_langganan_harga_awal',
        'idx_langganan_invoice_dates',
        'idx_langganan_last_invoice',
        'idx_langganan_method_created',
        'idx_langganan_method_dates',
        'idx_langganan_method_invoice',
        'idx_langganan_method_price',
        'idx_langganan_metode_pembayaran',
        'idx_langganan_package_created',
        'idx_langganan_package_dates',
        'idx_langganan_package_invoice',
        'idx_langganan_package_method',
        'idx_langganan_package_method_status',
        'idx_langganan_package_price',
        'idx_langganan_paket_layanan_id',
        'idx_langganan_payment_method',
        'idx_langganan_payment_status',
        'idx_langganan_pelanggan_id',
        'idx_langganan_price_filter',
        'idx_langganan_start_date',
        'idx_langganan_status',
        'idx_langganan_status_created',
        'idx_langganan_status_date',
        'idx_langganan_status_dates',
        'idx_langganan_status_invoice',
        'idx_langganan_status_method',
        'idx_langganan_status_package',
        'idx_langganan_status_price',
        'idx_langganan_tgl_berhenti',
        'idx_langganan_tgl_invoice_terakhir',
        'idx_langganan_tgl_mulai_langganan',
        'idx_langganan_updated_at',
        'idx_langganan_created_updated'
    ]

    for index_name in redundant_single_indexes:
        try:
            op.drop_index(index_name, table_name='langganan')
        except:
            pass  # Index might not exist, continue

    # Drop automatic indexes that were explicitly created
    auto_indexes = [
        'ix_langganan_created_at',
        'ix_langganan_harga_awal',
        'ix_langganan_id',
        'ix_langganan_metode_pembayaran',
        'ix_langganan_tgl_berhenti',
        'ix_langganan_tgl_invoice_terakhir',
        'ix_langganan_tgl_mulai_langganan',
        'ix_langganan_updated_at'
    ]

    for index_name in auto_indexes:
        try:
            op.drop_index(op.f(index_name), table_name='langganan')
        except:
            pass  # Index might not exist, continue

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
