"""add_payment_callback_log_table

Revision ID: 8c09acf411f3
Revises: f735203f82de
Create Date: 2025-09-22 20:09:02.945402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c09acf411f3'
down_revision: Union[str, Sequence[str], None] = 'f735203f82de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_callback_logs',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('idempotency_key', sa.String(length=255), nullable=True),
        sa.Column('xendit_id', sa.String(length=255), nullable=False),
        sa.Column('external_id', sa.String(length=255), nullable=False),
        sa.Column('callback_data', sa.String(length=1000), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_callback_logs_id', 'payment_callback_logs', ['id'], unique=False)
    op.create_index('ix_payment_callback_logs_xendit_id', 'payment_callback_logs', ['xendit_id'], unique=False)
    op.create_index('ix_payment_callback_logs_external_id', 'payment_callback_logs', ['external_id'], unique=False)
    op.create_index('ix_payment_callback_logs_idempotency_key', 'payment_callback_logs', ['idempotency_key'], unique=False)
    op.create_index('ix_payment_callback_logs_status', 'payment_callback_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_callback_logs_status', table_name='payment_callback_logs')
    op.drop_index('ix_payment_callback_logs_idempotency_key', table_name='payment_callback_logs')
    op.drop_index('ix_payment_callback_logs_external_id', table_name='payment_callback_logs')
    op.drop_index('ix_payment_callback_logs_xendit_id', table_name='payment_callback_logs')
    op.drop_index('ix_payment_callback_logs_id', table_name='payment_callback_logs')
    op.drop_table('payment_callback_logs')
    # ### end Alembic commands ###
