"""cleanup_mikrotik_server_over_indexing_optimize_performance

Revision ID: b71150711a61
Revises: 8481b912af1f
Create Date: 2025-10-04 17:40:07.420928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71150711a61'
down_revision: Union[str, Sequence[str], None] = '8481b912af1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop ALL the over-indexed indexes from mikrotik_servers table for MASSIVE performance boost!
    # WARNING: This will drop 70+ redundant indexes to improve write performance

    # Drop major composite indexes that are redundant
    redundant_indexes = [
        'idx_mikrotik_all_filters_extended',
        'idx_mikrotik_all_active_filters',
        'idx_mikrotik_all_created_updated_filters',
        'idx_mikrotik_all_name_created_updated_filters',
        'idx_mikrotik_all_host_created_updated_filters',
        'idx_mikrotik_all_user_created_updated_filters',
        'idx_mikrotik_all_port_created_updated_filters',
        'idx_mikrotik_all_version_created_updated_filters',
        'idx_mikrotik_all_status_created_updated_filters',
        'idx_mikrotik_all_active_created_updated_filters',
        'idx_mikrotik_all_created_filters',
        'idx_mikrotik_all_updated_filters',
        'idx_mikrotik_all_host_created_filters',
        'idx_mikrotik_all_user_created_filters',
        'idx_mikrotik_all_port_created_filters',
        'idx_mikrotik_all_version_created_filters',
        'idx_mikrotik_all_status_created_filters',
        'idx_mikrotik_all_active_created_filters',
        'idx_mikrotik_all_host_updated_filters',
        'idx_mikrotik_all_user_updated_filters',
        'idx_mikrotik_all_port_updated_filters',
        'idx_mikrotik_all_version_updated_filters',
        'idx_mikrotik_all_status_updated_filters',
        'idx_mikrotik_all_active_updated_filters',
        'idx_mikrotik_all_name_filters',
        'idx_mikrotik_all_host_filters',
        'idx_mikrotik_all_user_filters',
        'idx_mikrotik_all_port_filters',
        'idx_mikrotik_all_version_filters',
        'idx_mikrotik_all_status_filters',
        'idx_mikrotik_all_active_status_filters',
        'idx_mikrotik_version_active_status',
        'idx_mikrotik_name_host_port',
        'idx_mikrotik_host_user_port',
        'idx_mikrotik_active_host_port',
        'idx_mikrotik_name_active_host',
        'idx_mikrotik_host_user_active',
        'idx_mikrotik_user_port_active',
        'idx_mikrotik_name_user_active',
        'idx_mikrotik_host_version_active',
        'idx_mikrotik_name_version_active',
        'idx_mikrotik_user_version_active',
        'idx_mikrotik_port_version_active',
        'idx_mikrotik_host_status_active',
        'idx_mikrotik_name_status_active',
        'idx_mikrotik_user_status_active',
        'idx_mikrotik_port_status_active',
        'idx_mikrotik_version_status_active'
    ]

    for index_name in redundant_indexes:
        try:
            op.drop_index(index_name, table_name='mikrotik_servers')
        except:
            pass  # Index might not exist, continue

    # Drop redundant individual indexes
    redundant_single_indexes = [
        'idx_mikrotik_name_host',
        'idx_mikrotik_host_port',
        'idx_mikrotik_user_pass',
        'idx_mikrotik_active_version',
        'idx_mikrotik_status_version',
        'idx_mikrotik_active_host',
        'idx_mikrotik_name_active',
        'idx_mikrotik_host_active',
        'idx_mikrotik_user_active',
        'idx_mikrotik_port_active',
        'idx_mikrotik_created_at',
        'idx_mikrotik_updated_at'
    ]

    for index_name in redundant_single_indexes:
        try:
            op.drop_index(index_name, table_name='mikrotik_servers')
        except:
            pass  # Index might not exist, continue

    # Drop automatic indexes that were explicitly created
    auto_indexes = [
        'ix_mikrotik_servers_created_at',
        'ix_mikrotik_servers_id',
        'ix_mikrotik_servers_last_connected_at',
        'ix_mikrotik_servers_port',
        'ix_mikrotik_servers_ros_version',
        'ix_mikrotik_servers_updated_at',
        'ix_mikrotik_servers_username'
    ]

    for index_name in auto_indexes:
        try:
            op.drop_index(op.f(index_name), table_name='mikrotik_servers')
        except:
            pass  # Index might not exist, continue

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
