"""tambah metode pembayaran dan harga awal pada langganan

Revision ID: 0c8998c2254f
Revises: f6023d97fd5d
Create Date: 2025-07-20 18:39:39.343733

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0c8998c2254f'
down_revision: Union[str, Sequence[str], None] = 'f6023d97fd5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('langganan', sa.Column('metode_pembayaran', sa.String(length=50), server_default='Otomatis', nullable=False))
    op.add_column('langganan', sa.Column('harga_awal', sa.Numeric(precision=15, scale=2), nullable=True))
    op.create_foreign_key(None, 'pelanggan', 'harga_layanan', ['id_brand'], ['id_brand'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pelanggan', type_='foreignkey')
    op.drop_column('langganan', 'harga_awal')
    op.drop_column('langganan', 'metode_pembayaran')
    # ### end Alembic commands ###
