"""Penambahan Fitur Habis-Habisan

Revision ID: 1140a378c1ea
Revises: f95c6ea22406
Create Date: 2025-08-31 17:30:18.480511

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1140a378c1ea'
down_revision: Union[str, Sequence[str], None] = 'f95c6ea22406'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_data_teknis_pelanggan_id'), table_name='data_teknis')
    # op.create_index(op.f('ix_data_teknis_pelanggan_id'), 'data_teknis', ['pelanggan_id'], unique=True)
    # op.drop_index(op.f('ix_langganan_pelanggan_id'), table_name='langganan')
    # op.drop_index(op.f('ix_langganan_status'), table_name='langganan')
    # op.drop_index(op.f('ix_langganan_tgl_jatuh_tempo'), table_name='langganan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_langganan_tgl_jatuh_tempo'), 'langganan', ['tgl_jatuh_tempo'], unique=False)
    # op.create_index(op.f('ix_langganan_status'), 'langganan', ['status'], unique=False)
    # op.create_index(op.f('ix_langganan_pelanggan_id'), 'langganan', ['pelanggan_id'], unique=False)
    # op.drop_index(op.f('ix_data_teknis_pelanggan_id'), table_name='data_teknis')
    # op.create_index(op.f('ix_data_teknis_pelanggan_id'), 'data_teknis', ['pelanggan_id'], unique=False)
    # ### end Alembic commands ###
