"""models data_teknis indexing

Revision ID: 22d0a2c51221
Revises: 5e2953ebbf5a
Create Date: 2025-07-28 21:30:00.609246

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '22d0a2c51221'
down_revision: Union[str, Sequence[str], None] = '5e2953ebbf5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
#    op.create_index(op.f('ix_data_teknis_id_pelanggan'), 'data_teknis', ['id_pelanggan'], unique=False)
 #   op.create_index(op.f('ix_data_teknis_ip_pelanggan'), 'data_teknis', ['ip_pelanggan'], unique=False)
  #  op.create_index(op.f('ix_data_teknis_olt'), 'data_teknis', ['olt'], unique=False)
   # op.create_index(op.f('ix_data_teknis_pelanggan_id'), 'data_teknis', ['pelanggan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  #  op.drop_index(op.f('ix_data_teknis_pelanggan_id'), table_name='data_teknis')
  #  op.drop_index(op.f('ix_data_teknis_olt'), table_name='data_teknis')
  #  op.drop_index(op.f('ix_data_teknis_ip_pelanggan'), table_name='data_teknis')
  #  op.drop_index(op.f('ix_data_teknis_id_pelanggan'), table_name='data_teknis')
    # ### end Alembic commands ###
