"""add lat lon and parent relationship to odp

Revision ID: 484de7339bda
Revises: d8a621e86559
Create Date: 2025-09-01 13:59:29.554683

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '484de7339bda'
down_revision: Union[str, Sequence[str], None] = 'd8a621e86559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Menambahkan kolom-kolom baru ke tabel 'odp'
    op.add_column('odp', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('odp', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('odp', sa.Column('parent_odp_id', sa.Integer(), nullable=True))
    
    # Membuat foreign key constraint untuk relasi parent-child
    op.create_foreign_key(
        'fk_odp_parent_odp_id_odp', # Nama constraint
        'odp',                     # Tabel sumber
        'odp',                     # Tabel tujuan
        ['parent_odp_id'],         # Kolom sumber
        ['id']                     # Kolom tujuan
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Kebalikan dari proses upgrade, untuk rollback
    op.drop_constraint('fk_odp_parent_odp_id_odp', 'odp', type_='foreignkey')
    op.drop_column('odp', 'parent_odp_id')
    op.drop_column('odp', 'longitude')
    op.drop_column('odp', 'latitude')
    # ### end Alembic commands ###