"""Menambah kolom SN ke tabel data_teknis

Revision ID: 4cc22aad24ea
Revises: c969cfc56bf2
Create Date: 2025-08-11 15:17:36.747100

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cc22aad24ea"
down_revision: Union[str, Sequence[str], None] = "c969cfc56bf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_teknis", sa.Column("sn", sa.String(length=191), nullable=True))
    op.create_index(op.f("ix_data_teknis_sn"), "data_teknis", ["sn"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_data_teknis_sn"), table_name="data_teknis")
    op.drop_column("data_teknis", "sn")
    # ### end Alembic commands ###
