"""Sinkronisasi model dengan database

Revision ID: 4d557a9e8bbf
Revises: 1140a378c1ea
Create Date: 2025-08-31 17:57:38.761767

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

revision: str = '4d557a9e8bbf'
down_revision: Union[str, Sequence[str], None] = '1140a378c1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
# ... (info revisi)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # HAPUS ATAU BERI KOMENTAR PADA DUA BARIS INI
    # op.drop_index(op.f('ix_data_teknis_pelanggan_id'), table_name='data_teknis')
    # op.create_index(op.f('ix_data_teknis_pelanggan_id'), 'data_teknis', ['pelanggan_id'], unique=True)
    
    # BIARKAN BARIS INI KARENA INI PERUBAHAN YANG BENAR
    op.alter_column('langganan', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False,
               existing_server_default=sa.text("'Aktif'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # HAPUS ATAU BERI KOMENTAR PADA DUA BARIS INI JUGA
    # op.drop_index(op.f('ix_data_teknis_pelanggan_id'), table_name='data_teknis')
    # op.create_index(op.f('ix_data_teknis_pelanggan_id'), 'data_teknis', ['pelanggan_id'], unique=False)

    # BIARKAN BARIS INI
    op.alter_column('langganan', 'status',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'Aktif'"))
    # ### end Alembic commands ###