"""models nullable data_teknis

Revision ID: 4d9abec44fed
Revises: 0fb032da0654
Create Date: 2025-07-23 09:58:16.215663

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4d9abec44fed'
down_revision: Union[str, Sequence[str], None] = '0fb032da0654'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 #   op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
#    op.drop_table('activity_logs')
  #  op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
   # op.drop_table('system_logs')
    op.alter_column('data_teknis', 'pon',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('data_teknis', 'otb',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('data_teknis', 'odc',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('data_teknis', 'odp',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('data_teknis', 'onu_power',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_teknis', 'onu_power',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('data_teknis', 'odp',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('data_teknis', 'odc',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('data_teknis', 'otb',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('data_teknis', 'pon',
               existing_type=mysql.INTEGER(),
               nullable=False)
    #op.create_table('system_logs',
#    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
 #   sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
  #  sa.Column('level', mysql.VARCHAR(length=50), nullable=False),
  #  sa.Column('message', mysql.TEXT(), nullable=False),
  #  sa.PrimaryKeyConstraint('id'),
  #  mysql_collate='utf8mb4_0900_ai_ci',
  #  mysql_default_charset='utf8mb4',
  #  mysql_engine='InnoDB'
  #  )
    #op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    #op.create_table('activity_logs',
 #   sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
#    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
  #  sa.Column('timestamp', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
  #  sa.Column('action', mysql.VARCHAR(length=255), nullable=False),
  #  sa.Column('details', mysql.TEXT(), nullable=True),
  #  sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('activity_logs_ibfk_1')),
  #  sa.PrimaryKeyConstraint('id'),
  #  mysql_collate='utf8mb4_0900_ai_ci',
  #  mysql_default_charset='utf8mb4',
  #  mysql_engine='InnoDB'
  #  )
    #op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    # ### end Alembic commands ###
