"""models pelanggan alamat_index & id_brand

Revision ID: 5e2953ebbf5a
Revises: 9e69d20c3dca
Create Date: 2025-07-28 21:03:07.962076

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5e2953ebbf5a'
down_revision: Union[str, Sequence[str], None] = '9e69d20c3dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
#    op.create_index(op.f('ix_pelanggan_alamat'), 'pelanggan', ['alamat'], unique=False)
 #   op.create_index(op.f('ix_pelanggan_id_brand'), 'pelanggan', ['id_brand'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  #  op.drop_index(op.f('ix_pelanggan_id_brand'), table_name='pelanggan')
   # op.drop_index(op.f('ix_pelanggan_alamat'), table_name='pelanggan')
    # ### end Alembic commands ###
