"""add activity_logs table

Revision ID: 7b55743fbc96
Revises: 
Create Date: 2025-09-09 13:57:15.573871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7b55743fbc96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_langganan_pelanggan_id'), 'langganan', ['pelanggan_id'], unique=False)
    op.create_index(op.f('ix_langganan_status'), 'langganan', ['status'], unique=False)
    op.create_index(op.f('ix_langganan_tgl_jatuh_tempo'), 'langganan', ['tgl_jatuh_tempo'], unique=False)
    op.create_foreign_key(None, 'langganan', 'pelanggan', ['pelanggan_id'], ['id'])
    op.drop_column('odp', 'koordinat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odp', sa.Column('koordinat', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'langganan', type_='foreignkey')
    op.drop_index(op.f('ix_langganan_tgl_jatuh_tempo'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_status'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_pelanggan_id'), table_name='langganan')
    # ### end Alembic commands ###
