"""models pelanggan to_dict

Revision ID: 9e69d20c3dca
Revises: 4d9abec44fed
Create Date: 2025-07-24 08:39:24.022746

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e69d20c3dca'
down_revision: Union[str, Sequence[str], None] = '4d9abec44fed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
