"""add tgl_mulai_langganan to langganan table

Revision ID: b7d91180af7e
Revises: 2c047ee58128
Create Date: 2025-08-22 15:05:31.985830

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b7d91180af7e'
down_revision: Union[str, Sequence[str], None] = '2c047ee58128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('langganan', sa.Column('tgl_mulai_langganan', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('langganan', 'tgl_mulai_langganan')
    # ### end Alembic commands ###
