"""add payment method to invoices

Revision ID: be11afc1ace2
Revises: 0c8998c2254f
Create Date: 2025-07-21 11:17:40.328434

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be11afc1ace2'
down_revision: Union[str, Sequence[str], None] = '0c8998c2254f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('metode_pembayaran', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'metode_pembayaran')
    # ### end Alembic commands ###
