# File: alembic/versions/bf57018ff681_.py

"""empty message

Revision ID: bf57018ff681
Revises: 1140a378c1ea
Create Date: 2025-08-31 17:47:22.870033

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bf57018ff681'
down_revision: Union[str, Sequence[str], None] = '1140a378c1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'langganan', 'pelanggan', ['pelanggan_id'], ['id'])
    op.drop_index(op.f('ix_langganan_status'), table_name='langganan')
    # op.drop_index(op.f('ix_langganan_pelanggan_id'), table_name='langganan') # <--- DINONAKTIFKAN
    op.drop_index(op.f('ix_langganan_tgl_jatuh_tempo'), table_name='langganan')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### KODE YANG SUDAH DIPERBAIKI ###
    # Urutan downgrade adalah kebalikan dari upgrade

    # Langkah 1 (downgrade): Hapus foreign key
    with op.batch_alter_table('data_teknis', schema=None) as batch_op:
        batch_op.drop_constraint('data_teknis_ibfk_1', type_='foreignkey')

    # Langkah 2 (downgrade): Hapus index 'unique' yang baru
    op.drop_index(op.f('ix_data_teknis_pelanggan_id'), table_name='data_teknis')
    
    # Langkah 3 (downgrade): Buat kembali index lama yang 'non-unique'
    op.create_index(op.f('ix_data_teknis_pelanggan_id'), 'data_teknis', ['pelanggan_id'], unique=False)

    # Langkah 4 (downgrade): Buat kembali foreign key
    with op.batch_alter_table('data_teknis', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'data_teknis_ibfk_1',
            'pelanggan',
            ['pelanggan_id'],
            ['id']
        )
        
    # Perintah downgrade lainnya
    op.create_index(op.f('ix_langganan_tgl_jatuh_tempo'), 'langganan', ['tgl_jatuh_tempo'], unique=False)
    op.create_index(op.f('ix_langganan_status'), 'langganan', ['status'], unique=False)
    op.create_index(op.f('ix_langganan_pelanggan_id'), 'langganan', ['pelanggan_id'], unique=False)
    ### END ###
