"""Tangal Mulai untuk Prorate

Revision ID: c969cfc56bf2
Revises: e2df82dd7ed5
Create Date: 2025-08-01 21:16:05.811629

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c969cfc56bf2'
down_revision: Union[str, Sequence[str], None] = 'e2df82dd7ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # HANYA JALANKAN PERINTAH UNTUK MENAMBAH KOLOM
   # op.add_column('langganan', sa.Column('tanggal_mulai', sa.Date(), nullable=True))
    
    # BERI TANDA KOMENTAR ATAU HAPUS TIGA BARIS DI BAWAH INI
    # op.drop_index(op.f('ix_langganan_pelanggan_id'), table_name='langganan')
    # op.drop_index(op.f('ix_langganan_status'), table_name='langganan')
    # op.drop_index(op.f('ix_langganan_tgl_jatuh_tempo'), table_name='langganan')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # HAPUS JUGA BAGIAN YANG MENCOBA MEMBUAT KEMBALI INDEX
    # op.create_index(op.f('ix_langganan_tgl_jatuh_tempo'), 'langganan', ['tgl_jatuh_tempo'], unique=False)
    # op.create_index(op.f('ix_langganan_status'), 'langganan', ['status'], unique=False)
    # op.create_index(op.f('ix_langganan_pelanggan_id'), 'langganan', ['pelanggan_id'], unique=False)
    
    # HANYA SISAKAN PERINTAH UNTUK MENGHAPUS KOLOM
    op.drop_column('langganan', 'tanggal_mulai')
    
    # ### end Alembic commands ###