"""models MikrotikServer

Revision ID: e2df82dd7ed5
Revises: 22d0a2c51221
Create Date: 2025-07-28 21:42:28.530644

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2df82dd7ed5'
down_revision: Union[str, Sequence[str], None] = '22d0a2c51221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
#    op.drop_index(op.f('name'), table_name='mikrotik_servers')
#    op.create_index(op.f('ix_mikrotik_servers_host_ip'), 'mikrotik_servers', ['host_ip'], unique=False)
#    op.create_index(op.f('ix_mikrotik_servers_is_active'), 'mikrotik_servers', ['is_active'], unique=False)
#    op.create_index(op.f('ix_mikrotik_servers_last_connection_status'), 'mikrotik_servers', ['last_connection_status'], unique=False)
#    op.create_index(op.f('ix_mikrotik_servers_name'), 'mikrotik_servers', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
 #   op.drop_index(op.f('ix_mikrotik_servers_name'), table_name='mikrotik_servers')
 #   op.drop_index(op.f('ix_mikrotik_servers_last_connection_status'), table_name='mikrotik_servers')
  #  op.drop_index(op.f('ix_mikrotik_servers_is_active'), table_name='mikrotik_servers')
  #  op.drop_index(op.f('ix_mikrotik_servers_host_ip'), table_name='mikrotik_servers')
  #  op.create_index(op.f('name'), 'mikrotik_servers', ['name'], unique=True)
    # ### end Alembic commands ###
