"""Sinkronisasi final

Revision ID: f6023d97fd5d
Revises: 
Create Date: 2025-07-18 22:10:34.968575

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f6023d97fd5d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_invoices_pelanggan_id'), 'invoices', ['pelanggan_id'], unique=False)
    op.create_index(op.f('ix_invoices_status_invoice'), 'invoices', ['status_invoice'], unique=False)
    op.create_index(op.f('ix_invoices_tgl_jatuh_tempo'), 'invoices', ['tgl_jatuh_tempo'], unique=False)
    op.create_index(op.f('ix_invoices_xendit_external_id'), 'invoices', ['xendit_external_id'], unique=False)
    op.create_index(op.f('ix_langganan_pelanggan_id'), 'langganan', ['pelanggan_id'], unique=False)
    op.create_index(op.f('ix_langganan_status'), 'langganan', ['status'], unique=False)
    op.create_index(op.f('ix_langganan_tgl_jatuh_tempo'), 'langganan', ['tgl_jatuh_tempo'], unique=False)
    op.alter_column('mikrotik_servers', 'last_connected_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_pelanggan_email'), table_name='pelanggan')
    op.create_index(op.f('ix_pelanggan_email'), 'pelanggan', ['email'], unique=True)
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.drop_index(op.f('ix_pelanggan_email'), table_name='pelanggan')
    op.create_index(op.f('ix_pelanggan_email'), 'pelanggan', ['email'], unique=False)
    op.alter_column('mikrotik_servers', 'last_connected_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_langganan_tgl_jatuh_tempo'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_status'), table_name='langganan')
    op.drop_index(op.f('ix_langganan_pelanggan_id'), table_name='langganan')
    op.drop_index(op.f('ix_invoices_xendit_external_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_tgl_jatuh_tempo'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status_invoice'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_pelanggan_id'), table_name='invoices')
    # ### end Alembic commands ###
