"""Tambah model inventory dengan panjang string

Revision ID: f95c6ea22406
Revises: 
Create Date: 2025-08-31 14:06:21.628808

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f95c6ea22406'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_item_types_name'), 'inventory_item_types', ['name'], unique=True)
    op.create_table('inventory_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_statuses_name'), 'inventory_statuses', ['name'], unique=True)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('mac_address', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('item_type_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('pelanggan_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['item_type_id'], ['inventory_item_types.id'], ),
    sa.ForeignKeyConstraint(['pelanggan_id'], ['pelanggan.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['inventory_statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_index(op.f('ix_inventory_items_serial_number'), 'inventory_items', ['serial_number'], unique=True)
    op.create_table('inventory_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.drop_index(op.f('ix_data_teknis_pelanggan_id'), table_name='data_teknis')
    # op.create_index(op.f('ix_data_teknis_pelanggan_id'), 'data_teknis', ['pelanggan_id'], unique=True)
    # op.drop_index(op.f('ix_langganan_pelanggan_id'), table_name='langganan')
    # op.drop_index(op.f('ix_langganan_status'), table_name='langganan')
    # op.drop_index(op.f('ix_langganan_tgl_jatuh_tempo'), table_name='langganan')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_langganan_tgl_jatuh_tempo'), 'langganan', ['tgl_jatuh_tempo'], unique=False)
    # op.create_index(op.f('ix_langganan_status'), 'langganan', ['status'], unique=False)
    # op.create_index(op.f('ix_langganan_pelanggan_id'), 'langganan', ['pelanggan_id'], unique=False)
    # op.drop_index(op.f('ix_data_teknis_pelanggan_id'), table_name='data_teknis')
    # op.create_index(op.f('ix_data_teknis_pelanggan_id'), 'data_teknis', ['pelanggan_id'], unique=False)
    op.drop_table('inventory_history')
    op.drop_index(op.f('ix_inventory_items_serial_number'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('ix_inventory_statuses_name'), table_name='inventory_statuses')
    op.drop_table('inventory_statuses')
    op.drop_index(op.f('ix_inventory_item_types_name'), table_name='inventory_item_types')
    op.drop_table('inventory_item_types')
    # ### end Alembic commands ###
